name: Deploy Backend Prefeitura (PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Atualizar código via git
        run: |
          cd ~/actions-runner/_work/back-nest/back-nest

          if [ ! -d ".git" ]; then
            git clone https://github.com/Renan0eng-org/back-nest.git .
          else
            git pull origin main
          fi

      - name: Instalar dependências
        run: |
          cd ~/actions-runner/_work/back-nest/back-nest
          npm install --force

      - name: Prisma generate
        run: |
          cd ~/actions-runner/_work/back-nest/back-nest
          npx prisma generate

      - name: Build
        run: |
          cd ~/actions-runner/_work/back-nest/back-nest
          npm run build

      - name: Deploy com PM2
        run: |
          cd ~/actions-runner/_work/back-nest/back-nest
          pm2 stop back-prefeitura || true
          pm2 delete back-prefeitura || true
          pm2 start npm --name back-prefeitura -- start
          pm2 save